# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Uknow
description: "A Minimalist Responsive Theme for Jekyll"
url: "https://github.com/r-i-c-h/r-i-c-h.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# google_analytics: "UA-XXXXXXXXX-X"
# disqus_shortname: "your-disqus-name"

author:
  name: "Rich Werden"
  email: rich_@t_richwerden.com
  twitter_username: the_riz
  github_username:  r-i-c-h
  linkedin_username:  r-i-c-h

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
        layout: "post"

# Build settings
include: ["_exproj"]
destination: _site
paginate: 10
permalink: /:year/:title.html
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

# The following are for the jekyll-livereload gem setup so as to use it as a default
# To get site to build in github pages, remove these lines.
# If you don't want to use the livereload just delete the next two lines
livereload: true
reload_port: 5678

plugins:
  - jekyll-paginate